language: php

php:
  - 7.1
  - 7.2

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry phpenv config-rm xdebug.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-source --no-interaction

# setup application:
  - |
    cp .env.dist .env
    sed -i s/yii2-starter-kit\.dev/localhost:8080/ .env

before_script:
  - mysql -e 'CREATE DATABASE yii2_test_db'
  - php tests/codeception/bin/yii app/setup --interactive=0

script:
  - |
    php -S localhost:8080 > /dev/null 2>&1 &
    vendor/bin/codecept run
